name: Create Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: "Specify the version for the release"
                required: true
                default: 1.0.0
                type: string

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                goos: [linux, darwin, windows]
                goarch: [amd64, arm64]
                ext: [exe, ""]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.21.1

            - name: Build
              run: |
                  GOARCH=${{ matrix.goarch }} GOOS=${{ matrix.goos }} go build -o pixel-art-tools-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }} ./cmd/pixelArtTools/main.go

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: v${{ inputs.version }}
                  release_name: Release ${{ inputs.version }}
                  draft: false
                  prerelease: false

            - name: Upload Release Asset
              id: upload-release-asset
              uses: actions/upload-release-asset@v1
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: pixel-art-tools-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}
                  asset_name: pixel-art-tools-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}
                  asset_content_type: application/octet-stream
                  token: ${{ secrets.GITHUB_TOKEN }}
