name: Create Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: "Specify the version for the release"
                required: true
                default: 1.0.0
                type: string

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.21.1

            - name: Build for darwin/amd64
              run: GOARCH=amd64 GOOS=darwin go build -o ./publish/osx-x64 ./cmd/pixelArtTools/main.go

            - name: Build for darwin/arm64
              run: GOARCH=arm64 GOOS=darwin go build -o ./publish/osx-arm ./cmd/pixelArtTools/main.go

            - name: Build for linux/amd64
              run: GOARCH=amd64 GOOS=linux go build -o ./publish/linux-x64 ./cmd/pixelArtTools/main.go

            - name: Build for windows/amd64
              run: GOARCH=amd64 GOOS=windows go build -o ./publish/win-x64.exe ./cmd/pixelArtTools/main.go

            - name: Set execute permissions
              run: |
                  chmod +x ./publish/osx-x64
                  chmod +x ./publish/osx-arm
                  chmod +x ./publish/linux-x64
                  chmod +x ./publish/win-x64.exe
              working-directory: ${{ github.workspace }}

            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: v${{ inputs.version }}
                  release_name: Release ${{ inputs.version }}
                  draft: false
                  prerelease: false

            - name: Upload MacOS x64 Asset
              id: upload_macos_arm
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./publish/osx-x64
                  asset_name: pixel-art-tools-osx-x64
                  asset_content_type: application/octet-stream

            - name: Upload MacOS Arm Asset
              id: upload_macos_amd
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./publish/osx-arm
                  asset_name: pixel-art-tools-osx-arm
                  asset_content_type: application/octet-stream

            - name: Upload Linux Asset
              id: upload_linux
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./publish/linux-x64
                  asset_name: pixel-art-tools-linux-x64
                  asset_content_type: application/octet-stream

            - name: Upload Linux Asset
              id: upload_windows
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: ./publish/win-x64.exe
                  asset_name: pixel-art-tools-win-x64.exe
                  asset_content_type: application/octet-stream
